version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:current-22.04
    resource_class: medium
    environment:
      - CACHE_DIR: ~/build/wxWidgets/staticlib
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-{{ checksum ".circleci/scripts/build_wxwidgets.sh" }}
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y build-essential cmake libpulse-dev libgtk-3-dev freeglut3 freeglut3-dev libhamlib-dev
      - run:
          name: Build wxWidgets
          command: bash .circleci/scripts/build_wxwidgets.sh
      - run:
          name: Build LiquidDSP
          command: bash .circleci/scripts/build_liquiddsp.sh
      - run:
          name: Build SoapySDR
          command: bash .circleci/scripts/build_soapysdr.sh
      - run:
          name: Build CubicSDR
          command: bash .circleci/scripts/build_cubicsdr.sh
      - save_cache:
          key: cache-{{ checksum ".circleci/scripts/build_wxwidgets.sh" }}
          paths:
            - ~/build/wxWidgets/staticlib
